name = "FLOWVLM"
uuid = "1a3ff0be-0410-4572-aa62-b496bdd1f33b"
authors = ["Eduardo J. Alvarez <Edo.AlvarezR@gmail.com>"]
version = "2.0.0"

[deps]
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
CCBlade = "e1828068-15df-11e9-03e4-ef195ea46fa4"
# GeometricTools = "asdasd"
# AirfoilPrep = "asdasd"


[compat]
julia = "1.4"
CCBlade = "0.1.0"
